server:
  port: 8083
eureka.client.serviceUrl.defaultZone: http://127.0.0.1:8666/eureka/
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
spring.druid:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/cloud
  username: root
  password: 300900
  maxActive: 30
  minIdle: 5
  maxWait: 10000
  validationQuery: SELECT 'x'
  timeBetweenEvictionRunsMillis: 60000
  minEVictableIdleTimeMillis: 300000
spring:
  application:
    name: user
  redis:
    port: 6379
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 5
spring.image.url: http://127.0.0.1:8182/images
mybatis:
  mapper-locations: classpath:mapper/*.xml

#eureka.client.healthcheck.enabled: true
